const boardData = [
  {
    id: 1,
    title: '첫 번째 게시물',
    content: '첫 번째 게시물 내용입니다.',
    writer: '작성자123123123123',
    image: 'https://picsum.photos/id/1/200/200',
    date: '2022-05-10',
    commentCount: 5,
    likeCount: 10,
  },
  {
    id: 2,
    title: '두 번째 게시물',
    content: '두 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/2/200/200',
    date: '2022-05-10',
    commentCount: 3,
    likeCount: 7,
  },
  {
    id: 3,
    title: '세 번째 게시물',
    content: '세 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/3/200/200',
    date: '2022-05-09',
    commentCount: 2,
    likeCount: 12,
  },
  {
    id: 4,
    title: '네 번째 게시물',
    content: '네 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/4/200/200',
    date: '2022-05-08',
    commentCount: 1,
    likeCount: 5,
  },
  {
    id: 5,
    title: '다섯 번째 게시물',
    content: '다섯 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/5/200/200',
    date: '2022-05-05',
    commentCount: 4,
    likeCount: 9,
  },
  {
    id: 6,
    title: '여섯 번째 게시물',
    content: '여섯 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/6/200/200',
    date: '2022-05-04',
    commentCount: 2,
    likeCount: 15,
  },
  {
    id: 7,
    title: '일곱 번째 게시물',
    content: '일곱 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/7/200/200',
    date: '2022-05-04',
    commentCount: 7,
    likeCount: 20,
  },
  {
    id: 8,
    title: '여덟 번째 게시물',
    content: '여덟 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/8/200/200',
    date: '2022-05-03',
    commentCount: 3,
    likeCount: 6,
  },
  {
    id: 9,
    title: '아홉 번째 게시물',
    content: '아홉 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/9/200/200',
    date: '2022-05-03',
    commentCount: 1,
    likeCount: 8,
  },
  {
    id: 10,
    title: '열 번째 게시물',
    content: '열 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/10/200/200',
    date: '2022-05-01',
    commentCount: 1,
    likeCount: 8,
  },
  {
    id: 11,
    title: '첫 번째 게시물',
    content: '첫 번째 게시물 내용입니다.',
    writer: '작성자123123123123',
    image: 'https://picsum.photos/id/1/200/200',
    date: '2022-05-10',
    commentCount: 5,
    likeCount: 10,
  },
  {
    id: 12,
    title: '두 번째 게시물',
    content: '두 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/2/200/200',
    date: '2022-05-10',
    commentCount: 3,
    likeCount: 7,
  },
  {
    id: 13,
    title: '세 번째 게시물',
    content: '세 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/3/200/200',
    date: '2022-05-09',
    commentCount: 2,
    likeCount: 12,
  },
  {
    id: 14,
    title: '네 번째 게시물',
    content: '네 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/4/200/200',
    date: '2022-05-08',
    commentCount: 1,
    likeCount: 5,
  },
  {
    id: 15,
    title: '다섯 번째 게시물',
    content: '다섯 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/5/200/200',
    date: '2022-05-05',
    commentCount: 4,
    likeCount: 9,
  },
  {
    id: 16,
    title: '여섯 번째 게시물',
    content: '여섯 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/6/200/200',
    date: '2022-05-04',
    commentCount: 2,
    likeCount: 15,
  },
  {
    id: 17,
    title: '일곱 번째 게시물',
    content: '일곱 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/7/200/200',
    date: '2022-05-04',
    commentCount: 7,
    likeCount: 20,
  },
  {
    id: 18,
    title: '여덟 번째 게시물',
    content: '여덟 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/8/200/200',
    date: '2022-05-03',
    commentCount: 3,
    likeCount: 6,
  },
  {
    id: 19,
    title: '아홉 번째 게시물',
    content: '아홉 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/9/200/200',
    date: '2022-05-03',
    commentCount: 1,
    likeCount: 8,
  },
  {
    id: 20,
    title: '열 번째 게시물',
    content: '열 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/10/200/200',
    date: '2022-05-01',
    commentCount: 1,
    likeCount: 8,
  },
  {
    id: 21,
    title: '첫 번째 게시물',
    content: '첫 번째 게시물 내용입니다.',
    writer: '작성자123123123123',
    image: 'https://picsum.photos/id/1/200/200',
    date: '2022-05-10',
    commentCount: 5,
    likeCount: 10,
  },
  {
    id: 22,
    title: '두 번째 게시물',
    content: '두 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/2/200/200',
    date: '2022-05-10',
    commentCount: 3,
    likeCount: 7,
  },
  {
    id: 23,
    title: '세 번째 게시물',
    content: '세 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/3/200/200',
    date: '2022-05-09',
    commentCount: 2,
    likeCount: 12,
  },
  {
    id: 24,
    title: '네 번째 게시물',
    content: '네 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/4/200/200',
    date: '2022-05-08',
    commentCount: 1,
    likeCount: 5,
  },
  {
    id: 25,
    title: '다섯 번째 게시물',
    content: '다섯 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/5/200/200',
    date: '2022-05-05',
    commentCount: 4,
    likeCount: 9,
  },
  {
    id: 26,
    title: '여섯 번째 게시물',
    content: '여섯 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/6/200/200',
    date: '2022-05-04',
    commentCount: 2,
    likeCount: 15,
  },
  {
    id: 27,
    title: '일곱 번째 게시물',
    content: '일곱 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/7/200/200',
    date: '2022-05-04',
    commentCount: 7,
    likeCount: 20,
  },
  {
    id: 28,
    title: '여덟 번째 게시물',
    content: '여덟 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/8/200/200',
    date: '2022-05-03',
    commentCount: 3,
    likeCount: 6,
  },
  {
    id: 29,
    title: '아홉 번째 게시물',
    content: '아홉 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/9/200/200',
    date: '2022-05-03',
    commentCount: 1,
    likeCount: 8,
  },
  {
    id: 30,
    title: '열 번째 게시물',
    content: '열 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/10/200/200',
    date: '2022-05-01',
    commentCount: 1,
    likeCount: 8,
  },
  {
    id: 31,
    title: '첫 번째 게시물',
    content: '첫 번째 게시물 내용입니다.',
    writer: '작성자123123123123',
    image: 'https://picsum.photos/id/1/200/200',
    date: '2022-05-10',
    commentCount: 5,
    likeCount: 10,
  },
  {
    id: 32,
    title: '두 번째 게시물',
    content: '두 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/2/200/200',
    date: '2022-05-10',
    commentCount: 3,
    likeCount: 7,
  },
  {
    id: 33,
    title: '세 번째 게시물',
    content: '세 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/3/200/200',
    date: '2022-05-09',
    commentCount: 2,
    likeCount: 12,
  },
  {
    id: 34,
    title: '네 번째 게시물',
    content: '네 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/4/200/200',
    date: '2022-05-08',
    commentCount: 1,
    likeCount: 5,
  },
  {
    id: 35,
    title: '다섯 번째 게시물',
    content: '다섯 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/5/200/200',
    date: '2022-05-05',
    commentCount: 4,
    likeCount: 9,
  },
  {
    id: 36,
    title: '여섯 번째 게시물',
    content: '여섯 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/6/200/200',
    date: '2022-05-04',
    commentCount: 2,
    likeCount: 15,
  },
  {
    id: 37,
    title: '일곱 번째 게시물',
    content: '일곱 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/7/200/200',
    date: '2022-05-04',
    commentCount: 7,
    likeCount: 20,
  },
  {
    id: 38,
    title: '여덟 번째 게시물',
    content: '여덟 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/8/200/200',
    date: '2022-05-03',
    commentCount: 3,
    likeCount: 6,
  },
  {
    id: 39,
    title: '아홉 번째 게시물',
    content: '아홉 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/9/200/200',
    date: '2022-05-03',
    commentCount: 1,
    likeCount: 8,
  },
  {
    id: 40,
    title: '열 번째 게시물',
    content: '열 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/10/200/200',
    date: '2022-05-01',
    commentCount: 1,
    likeCount: 8,
  },
  {
    id: 41,
    title: '첫 번째 게시물',
    content: '첫 번째 게시물 내용입니다.',
    writer: '작성자123123123123',
    image: 'https://picsum.photos/id/1/200/200',
    date: '2022-05-10',
    commentCount: 5,
    likeCount: 10,
  },
  {
    id: 42,
    title: '두 번째 게시물',
    content: '두 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/2/200/200',
    date: '2022-05-10',
    commentCount: 3,
    likeCount: 7,
  },
  {
    id: 43,
    title: '세 번째 게시물',
    content: '세 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/3/200/200',
    date: '2022-05-09',
    commentCount: 2,
    likeCount: 12,
  },
  {
    id: 44,
    title: '네 번째 게시물',
    content: '네 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/4/200/200',
    date: '2022-05-08',
    commentCount: 1,
    likeCount: 5,
  },
  {
    id: 45,
    title: '다섯 번째 게시물',
    content: '다섯 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/5/200/200',
    date: '2022-05-05',
    commentCount: 4,
    likeCount: 9,
  },
  {
    id: 46,
    title: '여섯 번째 게시물',
    content: '여섯 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/6/200/200',
    date: '2022-05-04',
    commentCount: 2,
    likeCount: 15,
  },
  {
    id: 47,
    title: '일곱 번째 게시물',
    content: '일곱 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/7/200/200',
    date: '2022-05-04',
    commentCount: 7,
    likeCount: 20,
  },
  {
    id: 48,
    title: '여덟 번째 게시물',
    content: '여덟 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/8/200/200',
    date: '2022-05-03',
    commentCount: 3,
    likeCount: 6,
  },
  {
    id: 49,
    title: '아홉 번째 게시물',
    content: '아홉 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/9/200/200',
    date: '2022-05-03',
    commentCount: 1,
    likeCount: 8,
  },
  {
    id: 50,
    title: '열 번째 게시물',
    content: '열 번째 게시물 내용입니다.',
    writer: '작성자',
    image: 'https://picsum.photos/id/10/200/200',
    date: '2022-05-01',
    commentCount: 1,
    likeCount: 8,
  },
];

export default boardData;
